# Generated by Django 5.2.4 on 2026-10-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_category_id_alter_event_details_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for the event location', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for the event location', null=True),
        ),
    ]
